### PR TITLE
[ci] Make repository field in image parameterized

### PR DESCRIPTION
**Pull request by JosseVanDelm**
Downstream github forks can not enable CI since the build-docker workflows is hardcoded to push to the pulp-platform organization

### CODE REVIEW

**Comment by JosseVanDelm** [comment]
Could a person with github superpowers activate the build-docker flow please :pray: ?

**Comment by paulsc96** [comment]
> Could a person with github superpowers activate the `build-docker` flow please 🙏 ?

It seems I cannot do that manually. By design, we only want that job to run on master commits. You can try adding `pull_request` to the `on` field temporarily and see if the changes work as intended.

**Comment by JosseVanDelm** [comment]
> > Could a person with github superpowers activate the `build-docker` flow please 🙏 ?
> 
> It seems I cannot do that manually. By design, we only want that job to run on master commits. You can try adding `pull_request` to the `on` field temporarily and see if the changes work as intended.

Okay! I can revert it if everything works as expected, note that this one will build and push an image with a `pr-48` tag.

**Comment by colluca** [comment]
Closing this as the source branch has diverged significantly from the target.

**Pull request closed without merging**
