### PR TITLE
Added 3 polybench benchmarks to snitch: Covariance, Correlation and Atax

### PR DESCRIPTION
**Pull request by jpcf**
Do not merge it just now. I will continue working on this branch a bit longer. Just created the PR to set authorship.

### CODE REVIEW

**Comment by colluca** [comment]
> Do not merge it just now. I will continue working on this branch a bit longer. Just created the PR to set authorship.

Great. Then please convert it to a draft PR until then :)

**Review by paulsc96 — COMMENTED** [review]
Sorry for redrafting this; did not see it was undrafted.

Do I understand correctly that this uses an Occamy cluster configuration with FDIV/FSQRT enabled? I am currently exploring some architectural choices, but maybe we should converge on a single standard config for software.

**Comment by colluca** [comment]
> Do I understand correctly that this uses an Occamy cluster configuration with FDIV/FSQRT enabled? I am currently exploring some architectural choices, but maybe we should converge on a single standard config for software.

That is correct. But it was only convenient because with the LLVM toolchain we cannot disable lowering to FDIV and FSQRT instructions (cfr. GCC's `-mno-fdiv` flag). However, with Federico's recent extension we can revert to the default hardware configuration. Let's discuss this further in the next compiler meeting.

**Comment by colluca** [comment]
Succeeded by https://github.com/pulp-platform/snitch_cluster/pull/111.

**Pull request closed without merging**
